### ISSUE TITLE
Duplicated accessions in mitofish.12S.May2023.tsv

### ISSUE THREAD

**Issue by BELKHIR** [aomlomics/mitohelper#10]
Hi,

I found 255 duplicated accessions in the file mitofish.12S.May2023.tsv.
After taking a closer look at some duplicates, it seems that one of the sequence is the 12S and the second is a wider sequencing encompassing the 12S.

awk 'BEGIN{FS="\t"; OFS="\t"}{idents[$1]++}END{for (i in idents) {counts[idents[i]]++}; for (j in counts) print j, counts[j]}' mitofish.12S.May2023.tsv
1	47818 
2	255

Any idea ?

Thank's

**Comment by shenjean** [comment]
Hi Belkhir,

Thank you for your patience. I checked the 255 duplicated records and noticed that most of them (n=251) were erroneously caused by 16S rRNA false positives extracted from mitogenome annotations. I updated the [code](https://github.com/aomlomics/mitohelper/wiki/7.-Create-12S-and-COI-reference-files) used to retrieve the 12S rRNA genes (particularly, by removing the `s-RNA` search term and adding a pipe to remove any other 16S rRNA gene sequences `grep -v 16S`). These were removed in the [updated May2023 12S rRNA gene dataset](https://doi.org/10.5281/zenodo.8044667) and future data updates will be reviewed carefully for duplicates. Please note that four duplicated records (AP005998, KJ643927, NC_024573, OP326524) contain two copies of the 12S rRNA gene. These were retained in the [updated May2023 12S rRNA gene dataset](https://doi.org/10.5281/zenodo.8044667).

Here are the md5 checksum values for the updated files:
- mitofish.12S.May2023.tsv (48,076 records; md5:c2c61dabeab1ce9a2f3268b6376b244b)
- mitofish.12S.May2023_NR.fasta (md5:46940bbc6060b6fedfdef0d0c130d544)
- 12S-seqs-derep-uniq.qza (md5:36920cc2341fff8675729aebec94d3f8)
- 12S-tax-derep-uniq.qza (md5:acee23173f8e95d71f8bbb6be41adaac)
- 12S-16S-18S-seqs.qza  (md5:74b6186d668d59fb6f0a87e1fb0ec560)
- 12S-16S-18S-tax.qza (md5:c8fa9121b567398be16a689705f9650f)

Please note that besides this fix, there will not be a database update this month (June 2023). The next update is scheduled for July 2023 as part of a student training program.

**Comment by shenjean** [comment]
Hi @BELKHIR,

Thank you for your patience. I checked the 255 duplicated records and noticed that most of them (n=251) were erroneously caused by 16S rRNA false positives extracted from mitogenome annotations. I updated the [code](https://github.com/aomlomics/mitohelper/wiki/7.-Create-12S-and-COI-reference-files) used to retrieve the 12S rRNA genes (particularly, by removing the `s-RNA` search term and adding a pipe to remove any other 16S rRNA gene sequences `grep -v 16S`). These were removed in the [updated May2023 12S rRNA gene dataset](https://doi.org/10.5281/zenodo.8044667) and future data updates will be reviewed carefully for duplicates. Please note that four duplicated records (AP005998, KJ643927, NC_024573, OP326524) contain two copies of the 12S rRNA gene. These were retained in the [updated May2023 12S rRNA gene dataset](https://doi.org/10.5281/zenodo.8044667).

Here are the md5 checksum values for the updated files:
- mitofish.12S.May2023.tsv (48,076 records; md5:c2c61dabeab1ce9a2f3268b6376b244b)
- mitofish.12S.May2023_NR.fasta (md5:46940bbc6060b6fedfdef0d0c130d544)
- 12S-seqs-derep-uniq.qza (md5:36920cc2341fff8675729aebec94d3f8)
- 12S-tax-derep-uniq.qza (md5:acee23173f8e95d71f8bbb6be41adaac)
- 12S-16S-18S-seqs.qza  (md5:74b6186d668d59fb6f0a87e1fb0ec560)
- 12S-16S-18S-tax.qza (md5:c8fa9121b567398be16a689705f9650f)

Please note that besides this fix, there will not be a database update this month (June 2023). The next update is scheduled for July 2023 as part of a student training program.
